# Generated by Django 4.0.3 on 2022-09-16 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_automobilevo_color_automobilevo_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilevo',
            name='import_href',
        ),
    ]
