# Generated by Django 4.0.3 on 2022-09-16 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0003_remove_automobilevo_import_href'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salerecord',
            old_name='sales_person',
            new_name='salesperson',
        ),
    ]
