# Generated by Django 4.0.3 on 2022-09-17 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technician',
            name='employee_id',
        ),
        migrations.AlterField(
            model_name='technician',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
