# Generated by Django 4.0.3 on 2022-09-15 19:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0002_alter_appointment_technician'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='vin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service', to='service_rest.autovo'),
        ),
    ]
