# Generated by Django 4.0.3 on 2022-09-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service_rest', '0004_rename_customer_name_appointment_owner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(default='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(default='YYYY-MM-DD'),
        ),
        migrations.AlterField(
            model_name='autovo',
            name='year',
            field=models.SmallIntegerField(),
        ),
    ]
